INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk12', 'PR-JK2C81CD', 'snack', 'description satu', 10000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk13', 'PR-SJSGF0CJ', 'snack', 'description satu', 10000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk14', 'PR-B2PQGRAU', 'snack', 'description satu', 10000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk15', 'PR-DE7X09I3', 'snack', 'description satu', 10000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk16', 'PR-7S8UDZS1', 'snack', 'description satu', 10000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk17', 'PR-PC5D03R4', 'snack', 'description satu', 10000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk18', 'PR-QXAEV801', 'snack', 'description satu', 10000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk19', 'PR-XBWWP6EC', 'snack', 'description satu', 10000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk20', 'PR-3M4M000Y', 'snack', 'description satu', 10000, '2025-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES( 'produk1', 'PR-KXKC8EXJ', 'protein', 'description satu', 10000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES( 'produk2', 'PR-E8RNTUR0', 'protein', 'description satu', 20000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES( 'produk3', 'PR-S085H6P4', 'sayuran', 'description satu', 30000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES( 'produk4', 'PR-4N1JR0BS', 'sayuran', 'description satu', 40000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES( 'produk5', 'PR-Q0WJWZHN', 'sayuran', 'description satu', 50000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES( 'produk6', 'PR-3IAROZVO', 'buah', 'description satu', 60000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES( 'produk7', 'PR-A6MKMZ6B', 'buah', 'description satu', 70000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES( 'produk8', 'PR-RHN49U35', 'buah', 'description satu', 80000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES( 'produk9', 'PR-VC41SKL8', 'buah', 'description satu', 90000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk10', 'PR-4TTXTJZ7', 'buah', 'description satu', 100000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk11', 'PR-TFLOPJUB', 'snack', 'description satu', 110000, '2024-03-20');
INSERT INTO product ( name, product_code, product_type, description, price, register_date) VALUES ( 'produk90', 'PR-IBE3E8F0', 'snack', 'description satu', 10000, '2024-03-21');
